if vim.g.vscode then
	-- VSCode extension
	require("copocaneta.core.vscodesettings")
	-- require("copocaneta.plugins.vscodeeasymotion")
else
	print("Loading standard NeoVim configuration")
	require("copocaneta.plugins-setup")
	require("copocaneta.core.options")
	require("copocaneta.core.keymaps")
	-- ordinary Neovim
	require("copocaneta.core.telescopefoldfix")
	require("copocaneta.core.colorscheme")
	require("copocaneta.plugins.comment")
	require("copocaneta.plugins.nvim-tree")
	require("copocaneta.plugins.lualine")
	require("copocaneta.plugins.telescope")
	require("copocaneta.plugins.nvim-cmp")
	require("copocaneta.plugins.lsp.mason")
	require("copocaneta.plugins.lsp.lspsaga")
	require("copocaneta.plugins.lsp.lspconfig")
	require("copocaneta.plugins.lsp.null-ls")
	require("copocaneta.plugins.autopairs")
	require("copocaneta.plugins.treesitter")
	require("copocaneta.plugins.gitsigns")
	-- require("copocaneta.plugins.toggleterm-config")
	require("copocaneta.plugins.nvim-dap")
	require("copocaneta.plugins.dap-vscode-js")
	require("copocaneta.core.dap-js-setting")
	require("copocaneta.plugins.nvim-dap-ui")
end
